services:
  view:
    build:
      context: ./view
      dockerfile: Dockerfile
      target: dev
    working_dir: /app
    command: pnpm dev
    volumes:
      - ./view:/app
    ports:
      - "3000:3000"
    environment:
      GOOGLE_APPLICATION_CREDENTIALS: /secret/credentials.json
