# Cloud Run 専用サービスアカウント設定
# このファイルは手動でのGCP設定時に参考として使用

# 1. Cloud Run 専用サービスアカウントの作成
apiVersion: v1
kind: ConfigMap
metadata:
  name: cloud-run-setup-commands
data:
  create-service-account.sh: |
    #!/bin/bash
    
    # プロジェクトIDの設定
    PROJECT_ID="your-gcp-project-id"
    
    # Cloud Run 専用サービスアカウントの作成
    gcloud iam service-accounts create cloud-run-penlight \
      --display-name="Cloud Run Penlight Quiz Service Account" \
      --description="坂道ペンライトクイズアプリ用のCloud Runサービスアカウント" \
      --project="$PROJECT_ID"
    
    # BigQuery 読み取り専用権限の付与
    gcloud projects add-iam-policy-binding "$PROJECT_ID" \
      --member="serviceAccount:cloud-run-penlight@${PROJECT_ID}.iam.gserviceaccount.com" \
      --role="roles/bigquery.dataViewer"
    
    gcloud projects add-iam-policy-binding "$PROJECT_ID" \
      --member="serviceAccount:cloud-run-penlight@${PROJECT_ID}.iam.gserviceaccount.com" \
      --role="roles/bigquery.jobUser"
    
    # Cloud Logging 書き込み権限の付与
    gcloud projects add-iam-policy-binding "$PROJECT_ID" \
      --member="serviceAccount:cloud-run-penlight@${PROJECT_ID}.iam.gserviceaccount.com" \
      --role="roles/logging.logWriter"
    
    # Cloud Monitoring メトリクス書き込み権限の付与
    gcloud projects add-iam-policy-binding "$PROJECT_ID" \
      --member="serviceAccount:cloud-run-penlight@${PROJECT_ID}.iam.gserviceaccount.com" \
      --role="roles/monitoring.metricWriter"
    
    # サービスアカウントキーの作成（GitHub Secretsで使用）
    gcloud iam service-accounts keys create cloud-run-sa-key.json \
      --iam-account="cloud-run-penlight@${PROJECT_ID}.iam.gserviceaccount.com" \
      --project="$PROJECT_ID"
    
    echo "✅ サービスアカウント作成完了"
    echo "📝 cloud-run-sa-key.json をGitHub SecretsのGCP_SA_KEYに設定してください"

---

# 2. Artifact Registry の設定
apiVersion: v1
kind: ConfigMap
metadata:
  name: artifact-registry-setup
data:
  setup-registry.sh: |
    #!/bin/bash
    
    PROJECT_ID="your-gcp-project-id"
    REGION="asia-northeast1"
    REPOSITORY="penlight"
    
    # Artifact Registry リポジトリの作成
    gcloud artifacts repositories create "$REPOSITORY" \
      --repository-format=docker \
      --location="$REGION" \
      --description="坂道ペンライトクイズアプリ用Dockerイメージリポジトリ" \
      --project="$PROJECT_ID"
    
    # GitHub Actions 用サービスアカウントへの権限付与
    gcloud artifacts repositories add-iam-policy-binding "$REPOSITORY" \
      --location="$REGION" \
      --member="serviceAccount:cloud-run-penlight@${PROJECT_ID}.iam.gserviceaccount.com" \
      --role="roles/artifactregistry.writer" \
      --project="$PROJECT_ID"
    
    echo "✅ Artifact Registry セットアップ完了"

---

# 3. Secret Manager の設定（BigQuery認証情報用）
apiVersion: v1
kind: ConfigMap
metadata:
  name: secret-manager-setup
data:
  setup-secrets.sh: |
    #!/bin/bash
    
    PROJECT_ID="your-gcp-project-id"
    
    # BigQuery用サービスアカウントキーをSecret Managerに保存
    gcloud secrets create bigquery-sa-key \
      --replication-policy="automatic" \
      --project="$PROJECT_ID"
    
    # キーファイルの内容をシークレットに保存
    gcloud secrets versions add bigquery-sa-key \
      --data-file="cloud-run-sa-key.json" \
      --project="$PROJECT_ID"
    
    # Cloud Run サービスアカウントにシークレット読み取り権限を付与
    gcloud secrets add-iam-policy-binding bigquery-sa-key \
      --member="serviceAccount:cloud-run-penlight@${PROJECT_ID}.iam.gserviceaccount.com" \
      --role="roles/secretmanager.secretAccessor" \
      --project="$PROJECT_ID"
    
    echo "✅ Secret Manager セットアップ完了"

---

# 4. Cloud Run の IAM 設定
apiVersion: v1
kind: ConfigMap
metadata:
  name: cloud-run-iam-setup
data:
  setup-iam.sh: |
    #!/bin/bash
    
    PROJECT_ID="your-gcp-project-id"
    
    # GitHub Actions デプロイ用サービスアカウントの作成
    gcloud iam service-accounts create github-actions-deploy \
      --display-name="GitHub Actions Deploy Service Account" \
      --description="GitHub ActionsからCloud Runデプロイ用" \
      --project="$PROJECT_ID"
    
    # Cloud Run デプロイ権限の付与
    gcloud projects add-iam-policy-binding "$PROJECT_ID" \
      --member="serviceAccount:github-actions-deploy@${PROJECT_ID}.iam.gserviceaccount.com" \
      --role="roles/run.admin"
    
    # Artifact Registry 読み取り権限の付与
    gcloud projects add-iam-policy-binding "$PROJECT_ID" \
      --member="serviceAccount:github-actions-deploy@${PROJECT_ID}.iam.gserviceaccount.com" \
      --role="roles/artifactregistry.reader"
    
    # Service Account User 権限の付与（Cloud Runサービスを他のSAで実行するため）
    gcloud projects add-iam-policy-binding "$PROJECT_ID" \
      --member="serviceAccount:github-actions-deploy@${PROJECT_ID}.iam.gserviceaccount.com" \
      --role="roles/iam.serviceAccountUser"
    
    # GitHub Actions用キーの作成
    gcloud iam service-accounts keys create github-actions-key.json \
      --iam-account="github-actions-deploy@${PROJECT_ID}.iam.gserviceaccount.com" \
      --project="$PROJECT_ID"
    
    echo "✅ GitHub Actions IAM セットアップ完了"
    echo "📝 github-actions-key.json をGitHub SecretsのGCP_SA_KEYに設定してください"