apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: penlight
spec:
  project: default
  source:
    repoURL: 'https://github.com/AobaIwaki123/sakamichi-penlight-quiz'
    targetRevision: HEAD
    path: k8s/manifests
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: penlight
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
