apiVersion: apps/v1
kind: Deployment
metadata:
  name: penlight
spec:
  replicas: 1
  selector:
    matchLabels:
      app: penlight
  template:
    metadata:
      labels:
        app: penlight
    spec:
      imagePullSecrets:
        - name: harbor-pull-secret
      containers:
        - name: penlight
          image: harbor.aooba.net/penlight/prod-view-penlight:100.0.1
          volumeMounts:
            - name: gcp-sa-volume
              mountPath: /app/secret
              readOnly: true
          env:
            - name: GOOGLE_APPLICATION_CREDENTIALS
              value: /app/secret/key.json
          ports:
            - containerPort: 3000
      volumes:
        - name: gcp-sa-volume
          secret:
            secretName: gcp-sa-key
