name: Deploy Sakamichi Penlight Quiz
run-name: Deploy Sakamichi Penlight Quiz

on:
  workflow_dispatch:
    inputs:
      image_tag:
        description: "Docker image tag (e.g. tmp-1)"
        required: true
        default: tmp
  workflow_run:
    workflows: ["release-action"]
    types:
      - completed

env:
  HARBOR_REGISTRY: harbor.aooba.net
  IMAGE_NAME: penlight/prod-view-penlight
  DEPLOYMENT_FILE_PATH: k8s/manifests/deployment.yml

jobs:
  determine-image-tag:
    runs-on: ubuntu-latest
    outputs:
      image_tag: ${{ steps.set-tag.outputs.image_tag }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # タグ取得のため必須

      - name: Determine Docker image tag
        id: set-tag
        run: |
          if [[ "${{ github.event_name }}" == "workflow_dispatch" ]]; then
            echo "image_tag=${{ github.event.inputs.image_tag }}" >> "$GITHUB_OUTPUT"
          else
            latest_tag=$(git describe --tags --abbrev=0)
            echo "Using latest tag: $latest_tag"
            echo "image_tag=$latest_tag" >> "$GITHUB_OUTPUT"
          fi

  docker-build-and-push-to-harbor:
    runs-on: ubuntu-latest
    needs: determine-image-tag
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Harbor registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.HARBOR_REGISTRY }}
          username: robot$github-action-penlight
          password: ${{ secrets.HARBOR_TOKEN }}

      - name: Build and Push Docker image to Harbor
        uses: docker/build-push-action@v6
        with:
          context: ./view
          file: ./view/Dockerfile
          target: prod
          push: true
          tags: ${{ env.HARBOR_REGISTRY }}/${{ env.IMAGE_NAME }}:${{ needs.determine-image-tag.outputs.image_tag }}

  update-deployment-manifest:
    runs-on: ubuntu-latest
    needs: determine-image-tag
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up yq (YAML processor)
        uses: mikefarah/yq@v4

      - name: Update deployment YAML with new image tag
        run: |
          yq -i '.spec.template.spec.containers[0].image = "${{ env.HARBOR_REGISTRY }}/${{ env.IMAGE_NAME }}:${{ needs.determine-image-tag.outputs.image_tag }}"' "${{ env.DEPLOYMENT_FILE_PATH }}"
          echo "Updated image in ${{ env.DEPLOYMENT_FILE_PATH }}"

      - name: Commit and push deployment update
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add "${{ env.DEPLOYMENT_FILE_PATH }}"
          git commit -m "Update image tag to ${{ needs.determine-image-tag.outputs.image_tag }}"
          git push

  sync:
    runs-on: ubuntu-latest
    needs: 
    - docker-build-and-push-to-harbor
    - update-deployment-manifest
    steps:
      - name: Trigger ArgoCD sync via API
        env:
          ARGOCD_TOKEN: ${{ secrets.ARGOCD_TOKEN }}
        run: |
          curl -X POST https://argocd.aooba.net/api/v1/applications/penlight/sync \
            -H "Authorization: Bearer $ARGOCD_TOKEN" \
            -H "Content-Type: application/json"
