name: label
run-name: Lint Label
description: major, minor, patchいずれかのラベルが1つだけついているかどうかを判定する

on:
  pull_request:
    types:
      - synchronize
      - opened
      - reopened
  label:
    types:
      - created
      - edited
      - deleted

defaults:
  run:
    shell: bash

jobs:
  check-label:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Check PR labels
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PR_NUMBER: ${{ github.event.pull_request.number }}
        run: |
          pip install --quiet requests
          python check_labels.py
