name: pr
run-name: PR action
description: PRが作られた時のActionの挙動を確認する

on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
  label: 
    types:
      - created
      - edited
      - deleted

defaults: 
  run:
    shell: bash

jobs:
  pr:
    runs-on: ubuntu-latest
    steps:
      - uses: docker://agilepathway/pull-request-label-checker:latest
        with:
          one_of: major,minor,patch
          repo_token: ${{ secrets.GITHUB_TOKEN }}

      
