name: pr
run-name: PR action
description: PRが作られた時のActionの挙動を確認する

on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
      - labeled
      - unlabeled

defaults: 
  run:
    shell: bash

jobs:
  pr:
    runs-on: ubuntu-latest
    steps:
      - uses: docker://agilepathway/pull-request-label-checker:latest
        id: label
        with:
          one_of: major,minor,patch
          repo_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Echo label
        run: |
          echo "label: ${{ steps.label.outputs.label_check }}"
      
