name: release-action
run-name: Release action

on:
  workflow_dispatch:
    inputs:
      bump-level:
        type: choice
        options: [patch, minor, major]
        required: true
        description: Bump to patch or minor or major version
  pull_request:
    types:
      - closed
    branches:
      - main

permissions:
  contents: write
  pull-requests: read

defaults:
  run:
    shell: bash

jobs:
  release:
    if: >
      github.event_name == 'workflow_dispatch' ||
      (github.event_name == 'pull_request' && 
      github.event.pull_request.merged == true && 
      github.event.pull_request.base.ref == 'main')
    timeout-minutes: 5
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Check Labels
        if: github.event_name == 'pull_request'
        uses: mheap/github-action-required-labels@v5
        id: check-labels
        with:
          mode: exactly
          count: 1
          labels: |
            patch
            minor
            major

      - name: Determine Bump Level
        id: determine-bump
        run: |
          if [[ "${{ github.event_name }}" == "workflow_dispatch" ]]; then
            echo "::set-output name=bump_level::${{ github.event.inputs.bump-level }}"
          elif [[ "${{ steps.check-labels.outputs.labels }}" == *"major"* ]]; then
            echo "::set-output name=bump_level::major"
          elif [[ "${{ steps.check-labels.outputs.labels }}" == *"minor"* ]]; then
            echo "::set-output name=bump_level::minor"
          elif [[ "${{ steps.check-labels.outputs.labels }}" == *"patch"* ]]; then
            echo "::set-output name=bump_level::patch"
          else
            echo "No valid label found. Exiting."
            exit 1
          fi
      - name: Create and Push Tag
        env:
          USERNAME: github-actions[bot]
          EMAIL: github-actions[bot]@users.noreply.github.com
          BUMP_LEVEL: ${{ steps.determine-bump.outputs.bump_level }}
          # Personal Access Tokenを使用してタグ作成時に他のワークフローを起動可能にする
          GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}
        run: |
          git config --global user.name "${USERNAME}"
          git config --global user.email "${EMAIL}"
          version="$(.github/scripts/bump.sh "${BUMP_LEVEL}")"
          echo "Created version: ${version}"
